services:

  database:
    build: ./database
    container_name: postgres-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - back-network

  backend:
    build: ./simple-api-student
    container_name: simpleapi
    restart: unless-stopped

    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

    depends_on:
      - database

    networks:
      - front-network
      - back-network

  httpd:
    build: ./http-server
    container_name: apache

    environment:
      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: ${BACKEND_PORT}

    ports:
      - "80:80"

    depends_on:
      - backend

    networks:
      - front-network

  adminer:
    image: adminer
    container_name: adminer

    ports:
      - "8090:8080"

    depends_on:
      - database

    networks:
      - back-network

networks:
  front-network:
  back-network:

volumes:
  postgres-data: