services:

  database:
    build: ./database
    container_name: postgres-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - back-network

  backend-1:
    build: ./simple-api-student
    container_name: backend-1
    restart: unless-stopped

    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      INSTANCE_NAME: backend-1

    depends_on:
      - database

    networks:
      - front-network
      - back-network

  backend-2:
    build: ./simple-api-student
    container_name: backend-2
    restart: unless-stopped

    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      INSTANCE_NAME: backend-2

    depends_on:
      - database

    networks:
      - front-network
      - back-network

  front:
    build: ./front
    container_name: front
    restart: unless-stopped

    depends_on:
      - backend-1
      - backend-2

    networks:
      - front-network

  httpd:
    build: ./http-server
    container_name: apache
    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      - front
      - backend-1
      - backend-2

    networks:
      - front-network

  adminer:
    image: adminer
    container_name: adminer

    ports:
      - "8090:8080"

    depends_on:
      - database

    networks:
      - back-network

networks:
  front-network:
  back-network:

volumes:
  postgres-data: