---
- name: Launch backend
  community.docker.docker_container:
    name: simpleapi
    image: yassinegharbi2627/simpleapi:1.0
    state: started
    recreate: true

    env:
      SPRING_DATASOURCE_URL: "{{ spring_datasource_url }}"
      SPRING_DATASOURCE_USERNAME: "{{ spring_datasource_username }}"
      SPRING_DATASOURCE_PASSWORD: "{{ spring_datasource_password }}"

    networks:
      - name: front-network
      - name: back-network
