---
- name: Launch backend-1
  community.docker.docker_container:
    name: backend-1
    image: yassinegharbi2627/simpleapi:latest
    pull: true
    state: started
    recreate: true

    env:
      SPRING_DATASOURCE_URL: "{{ spring_datasource_url }}"
      SPRING_DATASOURCE_USERNAME: "{{ spring_datasource_username }}"
      SPRING_DATASOURCE_PASSWORD: "{{ spring_datasource_password }}"

    networks:
      - name: front-network
      - name: back-network

- name: Launch backend-2
  community.docker.docker_container:
    name: backend-2
    image: yassinegharbi2627/simpleapi:latest
    pull: true
    state: started
    recreate: true

    env:
      SPRING_DATASOURCE_URL: "{{ spring_datasource_url }}"
      SPRING_DATASOURCE_USERNAME: "{{ spring_datasource_username }}"
      SPRING_DATASOURCE_PASSWORD: "{{ spring_datasource_password }}"

    networks:
      - name: front-network
      - name: back-network