name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:

  build-and-push-backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.TOKEN_DOCKER }}" | docker login --username ${{ secrets.USER_NAME_DOCKER }} --password-stdin

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./TP1/simple-api-student
          push: true
          tags: |
            yassinegharbi2627/simpleapi:latest
            yassinegharbi2627/simpleapi:${{ github.run_number }}

  build-and-push-database:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.TOKEN_DOCKER }}" | docker login --username ${{ secrets.USER_NAME_DOCKER }} --password-stdin

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./TP1/database
          push: true
          tags: |
            yassinegharbi2627/database:latest
            yassinegharbi2627/database:${{ github.run_number }}

  build-and-push-httpd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.TOKEN_DOCKER }}" | docker login --username ${{ secrets.USER_NAME_DOCKER }} --password-stdin

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./TP1/http-server
          push: true
          tags: |
            yassinegharbi2627/httpd:latest
            yassinegharbi2627/httpd:${{ github.run_number }}

  deploy:
    needs:
      - build-and-push-backend
      - build-and-push-database
      - build-and-push-httpd

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Install Docker collection
        run: |
          ansible-galaxy collection install community.docker

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add server to known_hosts
        run: |
          ssh-keyscan yassine.gharbi.takima.school >> ~/.ssh/known_hosts

      - name: Create vars.yml from GitHub Secrets
        run: |
          cat > TP1/ansible/vars.yml << EOF
          postgres_db: "${{ secrets.POSTGRES_DB }}"
          postgres_user: "${{ secrets.POSTGRES_USER }}"
          postgres_password: "${{ secrets.POSTGRES_PASSWORD }}"

          spring_datasource_url: "${{ secrets.SPRING_DATASOURCE_URL }}"
          spring_datasource_username: "${{ secrets.SPRING_DATASOURCE_USERNAME }}"
          spring_datasource_password: "${{ secrets.SPRING_DATASOURCE_PASSWORD }}"

          backend_host: "${{ secrets.BACKEND_HOST }}"
          backend_port: "${{ secrets.BACKEND_PORT }}"
          EOF

      - name: Deploy with Ansible
        run: |
          cd TP1/ansible
          ansible-playbook -i inventories/setup.yml docker.yml