name: Continuous Delivery

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:

  build-and-push-backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.TOKEN_DOCKER }}" | docker login --username ${{ secrets.USER_NAME_DOCKER }} --password-stdin

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./TP1/simple-api-student
          push: true
          tags: |
            yassinegharbi2627/simpleapi:latest
            yassinegharbi2627/simpleapi:${{ github.run_number }}

  build-and-push-database:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.TOKEN_DOCKER }}" | docker login --username ${{ secrets.USER_NAME_DOCKER }} --password-stdin

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./TP1/database
          push: true
          tags: |
            yassinegharbi2627/database:latest
            yassinegharbi2627/database:${{ github.run_number }}

  build-and-push-httpd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.TOKEN_DOCKER }}" | docker login --username ${{ secrets.USER_NAME_DOCKER }} --password-stdin

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./TP1/http-server
          push: true
          tags: |
            yassinegharbi2627/httpd:latest
            yassinegharbi2627/httpd:${{ github.run_number }}
