name: CI devops 2025

on:
  push:
    branches:
      - main
      - develop

  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Maven tests
        run: cd TP1/simple-api-student && mvn clean verify

  sonar-analysis:
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: SonarCloud analysis
        run: cd TP1/simple-api-student && mvn -B clean verify sonar:sonar -Dsonar.projectKey=ENISSAY39_Dev_Ops_Gharbi_Yassine -Dsonar.organization=enissay39 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  build-and-push-docker-image:
    needs: sonar-analysis
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.TOKEN_DOCKER }}" | docker login --username ${{ secrets.USER_NAME_DOCKER }} --password-stdin

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./TP1/simple-api-student
          tags: yassinegharbi2627/simple-api:1.0
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./TP1/database
          tags: yassinegharbi2627/database:1.0
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push http
        uses: docker/build-push-action@v6
        with:
          context: ./TP1/http-server
          tags: yassinegharbi2627/httpd:1.0
          push: ${{ github.ref == 'refs/heads/main' }}